server.port=8080
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/mockinv?useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mockinv}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mockinv1234}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
spring.jpa.generate-ddl=false
stock.backend.base-url=${PYTHON_STOCK_API_BASE_URL:http://localhost:8000}
