apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-serve-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k-serve-app
  template:
    metadata:
      labels:
        app: k-serve-app
    spec:
      containers:
        - name: app
          image: java-k-serve-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: k-serve-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: k-serve-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: k-serve-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k-serve-secret
                  key: SPRING_DATASOURCE_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
