apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: k-serve-config
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: k-serve-config
                  key: MARIADB_USER
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k-serve-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k-serve-secret
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
