apiVersion: v1
kind: Secret
metadata:
  name: k-serve-secret
type: Opaque
stringData:
  DB_PASSWORD: "12345678!!"
  MARIADB_ROOT_PASSWORD: "12345678!!"
  MARIADB_PASSWORD: "12345678!!"
  SECRET_KEY: "dev-secret-change-me"
  CMC_API_KEY: "89a4ffe3-03a9-4184-87e0-49214b000b99"
  ANTHROPIC_API_KEY: ""
