apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-mock-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: crypto-mock-app
  template:
    metadata:
      labels:
        app: crypto-mock-app
    spec:
      containers:
        - name: app
          image: 086015456585.dkr.ecr.ap-northeast-2.amazonaws.com/java-crypto-mock:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crypto-mock-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: PYTHON_STOCK_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: crypto-mock-config
                  key: PYTHON_STOCK_API_BASE_URL
          readinessProbe:
            httpGet:
              path: /api/member/me
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/member/me
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
