apiVersion: v1
kind: ConfigMap
metadata:
  name: k-serve-config
data:
  DB_HOST: dbms.edumgt.co.kr
  DB_PORT: "3306"
  DB_NAME: mockinv
  DB_USER: root
  MARIADB_DATABASE: mockinv
  MARIADB_USER: mockinv
