apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-mock-config
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://dbms.edumgt.co.kr:3306/mockinv?useUnicode=true&characterEncoding=utf8
  SPRING_DATASOURCE_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MARIADB_DATABASE: mockinv
  MARIADB_USER: mockinv
