apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crypto-mock

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - python-deployment.yaml
  - python-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress-alb.yaml
