apiVersion: v1
kind: Secret
metadata:
  name: k-serve-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "12345678!!"
  MARIADB_ROOT_PASSWORD: "12345678!!"
  MARIADB_PASSWORD: "12345678!!"
