apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k-serve-dev

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: k-serve
    patch: |-
      - op: replace
        path: /metadata/name
        value: k-serve-dev
  - target:
      kind: Deployment
      name: k-serve-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: java-k-serve-app:dev
  - target:
      kind: PersistentVolumeClaim
      name: mariadb-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi
